### ISSUE TITLE
Made some drone models

### ISSUE THREAD

**Issue by Haze33E** [suppergerrie2/ModJam5#13]
I tried my hand at making some models for the drones in blockbench. If I knew how to code and texture I would test them out. I tried making the drones look similar but different from one another so it's not just textures that make them look different from each other. Feel free to use them in your mod they just need textures.
 
[Drone 2.0 models.zip](https://github.com/suppergerrie2/ModJam5/files/2256595/Drone.2.0.models.zip)

**Comment by suppergerrie2** [comment]
Thank you! I'd love to check them out, but entities don't use json (Which I don't like but whatever). I'll see if I can import them as blockmodels and if I like them I can try remaking them for entities. (I use [tabula](https://minecraft.curseforge.com/projects/tabula-minecraft-modeler) to create them)

**Comment by Haze33E** [comment]
I'll check out tabula and try making them again if I can figure it out.

**Comment by suppergerrie2** [comment]
If you want to do that, that would be amazing! I'll ofcourse give credit to you (except if you don't want to).

**Comment by Haze33E** [comment]
Well I figured out tabula enough to make the models there's no textures though. If you like the models go ahead and use them. As for credit if you want to give it to me go ahead.
[drone 2.0 tabula models.zip](https://github.com/suppergerrie2/ModJam5/files/2256917/drone.2.0.tabula.models.zip)

**Comment by suppergerrie2** [comment]
I'll have to modify some stuff ( like making it 1 block big and then scaling it down for the textures to work correctly). So it'll take a while before I can put it in. I'll post an update on this issue with a beta version for you to check out when I'm done!

**Comment by Haze33E** [comment]
Was looking at the drones again to make sure I didn't mess up. Apparently a couple of the models disappeared I guess I didn't save them. Also a model has a part slightly misplaced piece I'll have to remake the two and fix the other and re-upload them

**Comment by suppergerrie2** [comment]
I am currently on the hauler drone (I am now making the basic texture, which will make it easier to change it later)

**Comment by Haze33E** [comment]
Ok I went through and remade the two missing models and realigned the parts on some models. I was using this program for the first time today so I wasn't removing the models the correct way when I started on a new one. So when I saved them it wound up saving empty files. 
[drone 2.0 tabula models fixed.zip](https://github.com/suppergerrie2/ModJam5/files/2257420/drone.2.0.tabula.models.fixed.zip)

**Comment by suppergerrie2** [comment]
Thanks! (I keep losing progress because I accidentally press esc and it quits the program)

**Comment by suppergerrie2** [comment]
I've added the archer drone and hauler drone models. I used very basic textures (almost the same as the versions now). If possible, could you check if the models are the same as you intended? 

!!!DON'T use this version in a normal world. It only has 2 drone types and if you use it in a normal world every other drone type will be deleted!!!
[sdrones-1.2.0 MODEL DEBUG.zip](https://github.com/suppergerrie2/ModJam5/files/2257629/sdrones-1.2.0.MODEL.DEBUG.zip)

**Comment by Haze33E** [comment]
Just gave them a look they look fine to me. The differences should be more noticeable with all the types added.

**Comment by suppergerrie2** [comment]
Yeah it takes a while to add them because I have to edit each element to set the dimensions correct and the custom scale to 1.0 and make them 2 times as big. Else the texture is very small

**Comment by suppergerrie2** [comment]
Closing because the new models are added :D (c4f45243e14f08866f1af3609d1b49eccf7417f2)
