### ISSUE TITLE
Add a way to select working area for farmer drones

### ISSUE THREAD

**Issue by Haze33E** [suppergerrie2/ModJam5#14]
No idea if this is possible just an idea I had for crop farm and tree farm drones.

It would be great if there was an item we could place on the ground to establish their zone of operation. Like imagine placing 4 torches (just an example) and the area between the torches is where the drones are allowed to plant and harvest crops/chop trees. This would allow you to have their home/chest in an area outside the farming area. But you'd need to have separate "torches" for crop farm drones and tree farm drones. Then make it so the drones only farm in the nearest farm area to their home so drones don't run off to a different farming area.

This would allow for larger or smaller farms and to not have chests in the middle of them.

**Comment by suppergerrie2** [comment]
Could be an interesting mechanic. I'd probably make it so the chest has to be next to a torch tho. At the moment I am not sure if it would be better than how I am doing it now. I now have a range exactly the correct size (so the water is never to far away).

**Comment by Haze33E** [comment]
Yeah I know you made their home area to match the water dispersal but it limits the size of a crop farm. From observing the crop farm drones most of the time they are just sitting on their chest with nothing to do. If they had to manage a larger crop field they would actually be harvesting and planting more often raising productivity.

Right now making an automated farm using villagers is more productive then using the crop farm drones. Just because they are limited in the area they are able to plant and harvest crops. The tree farm drones don't have the problem of productivity. I just don't like having the chests in the farm taking up space.

**Comment by suppergerrie2** [comment]
The size is limited because I haven't added upgrades yet. The code supports bigger sizes, but only specific ranges. 

Also the chest doesn't take up space, you couldn't place seeds there because of the water.

**Comment by suppergerrie2** [comment]
You'd still need a chest for when their inventory is full. But I'll show you later today how big the area will be with 1 range upgrade

**Comment by suppergerrie2** [comment]
![image](https://user-images.githubusercontent.com/15769860/44616576-95465800-a852-11e8-867c-5651be3eab15.png)
This would be the area after 1 area/range upgrade. A lot bigger!

**Comment by suppergerrie2** [comment]
![image](https://user-images.githubusercontent.com/15769860/44616594-d9395d00-a852-11e8-8b75-d3c9368ca646.png)
With the water around it the spot in the middle can still not be used for planting seeds, so the chest doesn't use planting space.

**Comment by Haze33E** [comment]
That increased farm size is nice it would be about the perfect size.  And I know what you mean about the chest not taking space but doesn't that have more to do with the coding for the drone. Some line of code telling the drone to ignore tilling the dirt in the home location.

**Comment by suppergerrie2** [comment]
I placed farmland in the whole square and that square in the middle turned to dirt because it didn't have water

**Comment by Haze33E** [comment]
Oh yeah I forgot wet farmland only forms 4 blocks from a water source the middle is 5 blocks from the edge.

**Comment by suppergerrie2** [comment]
I think this issue has been solved with the addition of the upgrade system.
