### ISSUE TITLE
Dumb Farming AI

### ISSUE THREAD

**Issue by VirxEC** [suppergerrie2/ModJam5#25]
Mod version: 1.3.1

Forge version: 14.23.5.2810

Java version: Java 8

Minecraft version: 1.12.2

What happened? The farming drone AI is kind of dumb. If you place one on top of a farm block, it will break it, place water, and break all of the surrounding farm blocks.

What did you expect to happen? The farming drones should be able to communicate so you can just spam place the drones and they will be able to communicate and not destroy everything. They should also be able to place crops.

How to reproduce? Spam place farming drones and let chaos ensue.
![It's chaos! (screenshot)](https://user-images.githubusercontent.com/35614515/54064007-a77c5800-41de-11e9-96f1-7dc622cf07ce.png)

**Comment by suppergerrie2** [comment]
This is WAI, drones will work around their home, and their home is set to where you spawn them (you can change it with the drone stick tho). So if you spam them on the farm land they will start making their farm area around where you placed them (which should be a chest).

There should be a better way to show this yeah, I'm thinking of changing the system so their home isn't where you place them but they work with jobs and job sites.
