### ISSUE TITLE
Develop enviroment

### ISSUE THREAD

**Issue by cr998** [suppergerrie2/ModJam5#3]
I don`t know if it is the right place to ask this.

I can`t configure develop enviroment whit this code, could you explain how have you set up this?

**Comment by suppergerrie2** [comment]
I didn't commit everything needed for development, just the code. If you setup a workspace using forge as shown [here](http://mcforge.readthedocs.io/en/latest/gettingstarted/) and then import the code in src/main it should work. 

I am now checking what the best way is to change the repository so this will be easier.

**Comment by suppergerrie2** [comment]
I added the gradle files so you should be able to run `gradlew setupDecompWorkspace` and if you use eclipse `gradlew eclipse` to setup a workspace.

**Comment by cr998** [comment]
Thanks, Im going to prove as you tell and i feedback in a few minutes

**Comment by suppergerrie2** [comment]
Let me know if it doesn't work! 😀

**Comment by cr998** [comment]
Sorry, I had a hard day's work I'm going to try now

**Comment by cr998** [comment]
I finaly ca setup my develop enviroment, thanks for the help

Now i can do more pull requests

**Comment by suppergerrie2** [comment]
Cool! I'll close this issue now if it is working.
