### ISSUE TITLE
Fuel system

### ISSUE THREAD

**Issue by cr998** [suppergerrie2/ModJam5#6]
Easy system of energy for the drones

**Comment by suppergerrie2** [comment]
I will have to think about. I didn't use rf to keep it simpler for the user to have a lot of drones. Could maybe make it use coal or something but I'm not sure if that would be more fun or just more grinding to use a lot of them

**Comment by cr998** [comment]
I had been thinking about it.

I think it's a good idea to implement an energy system because it would be a bit tricky to use the mod, because out of nowhere the drones do the work for you

**Comment by suppergerrie2** [comment]
What do you think is better? Make them run on items like wood and coal or implement some rf power system. The power system would make it a lot more complicated because you need to have a place for the drones to recharge and implement a generator to generate the rf.

**Comment by cr998** [comment]
I think that is better implement rf but at the moment this is a little mod, don`t complicate it, it is better to make this fuel as coal

**Comment by suppergerrie2** [comment]
I'll start working on a test with fuel next week (or earlier depending on when I release the update)

**Comment by suppergerrie2** [comment]
I've started working on a basic system, what would you think is a good way to display how much fuel it has left? Displaying as items above them probably won't work there are already a lot of items displaying.

**Comment by suppergerrie2** [comment]
I've been messing around with the fuel idea but it doesn't feel right. If I implement a fuel system it should probably be with RF and not with burnable items (It totally messes up the tree farms lol)

**Comment by cr998** [comment]
what do you think on a basic charging station near the home of the bots

**Comment by suppergerrie2** [comment]
I've also been thinking about that. But I want the mod to be usable without another mod installed for power generation. So I would have to add an option to disable the need for fuel and automatically detect if a power generation mod is installed.

**Comment by cr998** [comment]
this is a good idea
