### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by cr998** [suppergerrie2/ModJam5#9]
Is it a good to implement a continuous integration system, such as travisCI?

**Comment by suppergerrie2** [comment]
I'll have to look into that, have no idea how I would do that. If you know how please help :D

**Comment by suppergerrie2** [comment]
I may have something setup, I don't know if it will work but we'll see.

**Comment by cr998** [comment]
I will try to test it this night

**Comment by suppergerrie2** [comment]
I think this has been done. Will close the issue now
